### ISSUE TITLE
Node.js 10系統のサポート

### ISSUE THREAD

**Issue by 515hikaru** [515hikaru/pnovel#43]
やれるならやった方がいいよね

**Comment by 515hikaru** [comment]
`Array#flat` は Node.js 10 では使えないらしい。

Babel と Jest の設定をちゃんとすれば動くのではないかと思ったが、一旦は無視することにした

```
% npm run test 

> pnovel@0.4.5-dev test /home/hikaru/ghq/src/github.com/515hikaru/pnovel
> jest

 FAIL  __tests__/parser_test.js
  ● parser › parse testing

    TypeError: l.flat is not a function

      1030 | 
      1031 |     function makeLine(l) {
    > 1032 |       const chars = l.flat(2)
           |                       ^
      1033 |       return chars.join("").trim().replace(/(\r\n|\n|\r)/gm, "")
      1034 |     }
      1035 | 

      at makeLine (parser/parser.js:1032:23)
      at peg$c5 (parser/parser.js:158:21)
      at peg$parsesentence (parser/parser.js:694:14)
      at peg$parseblock (parser/parser.js:384:16)
      at peg$parsedoc (parser/parser.js:357:10)
      at peg$startRuleFunction (parser/parser.js:347:10)
      at peg$parse (parser/parser.js:1042:16)
      at Object.test (__tests__/parser_test.js:53:12)

 PASS  __tests__/eval_test.js

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 5 passed, 6 total
Snapshots:   0 total
Time:        1.262 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pnovel@0.4.5-dev test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pnovel@0.4.5-dev test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hikaru/.npm/_logs/2020-05-26T14_26_11_918Z-debug.log
```

**Comment by 515hikaru** [comment]
無理にしなくて良い気がしてきた。対応しない。
